name: "Setup Conda"
description: "Create conda environment for GitHub Action Job"

runs:
    using: "composite"
    steps:
        - uses: mamba-org/setup-micromamba@v2
          env:
              # Increase this value to reset cache if ./conda/conda-lock.yml has not changed
              CACHE_NUMBER: 0
          with:
              environment-file: ./conda/conda-lock.yml
              environment-name: cryocloud
              # only cache environment
              cache-environment: true
              cache-downloads: false
              cache-environment-key: ${{ runner.os }}-conda-environment-${{ env.CACHE_NUMBER }}-${{ hashFiles('./conda/conda-lock.yml') }}
