name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]
    # Add "edited" type for test purposes. Where possible, avoid using to prevent processing unnecessary events.
    # types: [created, edited]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  slashCommandDispatch:
    permissions:
      pull-requests: write  # for peter-evans/slash-command-dispatch to create PR reaction
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      # Generate token from CryoInTheCloud bot
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            condalock
          issue-type: pull-request
          permission: none
