name: Test

on:
  schedule:
    # run this once a week (sunday midnight) to preserve cache
    # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    - cron:  '0 0 * * 0'
  pull_request_target:
    types: [labeled, synchronize]
    paths:
      - '.github/**/*'
      - '{{ cookiecutter.repo_directory }}/**'
      - 'book/**'
      - 'conda/**'
      - 'scripts/**'
      - 'cookiecutter.yaml'
    branches:
      - main

jobs:
  build-and-test:
    # This workflow accesses secrets (~/.netrc) so only run if labelled by repo owner
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: contains(github.event.pull_request.labels.*.name, 'preview')

    name: Build and test on OS - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure NASA Earthdata Login
      env:
        EARTHDATA_USER: ${{ secrets.EARTHDATA_USER}}
        EARTHDATA_PASS: ${{ secrets.EARTHDATA_PASS }}
      run: |
        echo "machine urs.earthdata.nasa.gov login $EARTHDATA_USER password $EARTHDATA_PASS" > ~/.netrc
        chmod 0600 ~/.netrc

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: true
        publish-to-gh: false
        jb-save: true
